sudo: false
language: ruby
rvm:
  - 2.2.2
before_install: gem install bundler -v 1.13.6

before_script: 'bundle install'
script: 'bundle exec cucumber'

branches:
  only:
    - bdd
 
notifications:
  email:
    - edward@jualo.com
    - edward.fer@gmail.com